Repository 2025-contribution-nextjs-team5/ossca-team_nextjs, pull requests merged in 2025-06, with the labels that each got.

#92 feat: 메인 페이지 제작 (#71)
  package-lock.json
  package.json
  src/app/MainContent.tsx
  src/app/MainTemplate.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/mainFrames/Frame1.tsx
  src/mainFrames/Frame2.tsx
  src/mainFrames/Frame3.tsx
  src/mainFrames/Frame4.tsx
Labels: ✨ Feature

#79 [WEB-66] refactor: Header 컴포넌트 리팩토링
  src/app/common/AppDropdownButton.tsx
  src/app/common/AppHeader.tsx
  src/app/common/AppHeaderBottomBar.tsx
  src/app/common/DropDownButton.tsx
Labels: 🔨 Refactor

#98 refactor: Header 컴포넌트 리팩토링
  src/app/common/AppDropdownButton.tsx
  src/app/common/AppHeader.tsx
  src/app/common/AppHeaderBottomBar.tsx
  src/app/common/DropDownButton.tsx
Labels: 🔨 Refactor

#103 [WEB-76] layout에 패딩값 추가
  src/app/layout.tsx
  src/mainFrames/Frame1.tsx
Labels: 🎨 Html&css

#104 [WEB-56] posting 페이지 구현
  .github/ISSUE_TEMPLATE/1-issue-form.yml
  .github/ISSUE_TEMPLATE/2-bug-form.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  eslint.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/globals.css
  src/app/posting/[slug]/page.tsx
  src/app/posting/components/ArticleSnippet.tsx
  src/app/posting/components/MdxStyle.tsx
  src/app/posting/page.tsx
  src/app/search/page.tsx
  src/lib/github.ts
  tsconfig.json
Labels: ✨ Feature

#116 Revert "feat: Posting 페이지 검색 기능 적용 (#96)" 취소
  package-lock.json
  package.json
  src/app/common/SearchBar.tsx
  src/app/posting/PostingTemplate.tsx
  src/app/posting/components/NotFound.tsx
  src/app/posting/page.tsx
  src/app/search/SearchPageTemplate.tsx
  src/app/search/page.tsx
Labels: 🌏 Deploy

#118 fix: build 오류 해결
  .coderabbit.yaml
  package-lock.json
  src/app/search/page.tsx
Labels: 🐞 BugFix, :test_tube: Test

#123 refactor: AppHeaderBottomBar 상태 변경
  package-lock.json
  package.json
  src/app/common/AppDropdownButton.tsx
  src/app/common/AppHeader.tsx
  src/app/common/AppHeaderBottomBar.tsx
  src/app/mainFrames/Frame4.tsx
Labels: 🔨 Refactor

#141 [WEB-65] style : z-index값, Reflection gird값 수정
  src/app/developers/DevelopersTemplate.tsx
  src/app/developers/components/DevelopersIntroCard.tsx
Labels: 🎨 Html&css
